# Generated by Django 3.2 on 2021-05-10 18:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0003_test'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Courses',
            new_name='Course',
        ),
        migrations.DeleteModel(
            name='test',
        ),
    ]
