# Generated by Django 3.2 on 2021-05-10 19:11

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0004_auto_20210510_1358'),
    ]

    operations = [
        migrations.AddField(
            model_name='course',
            name='thumbnail_url',
            field=models.URLField(default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
