# Generated by Django 3.2 on 2021-06-04 21:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0006_your_course'),
    ]

    operations = [
        migrations.CreateModel(
            name='Suggest_Course',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=150)),
                ('email', models.EmailField(max_length=150)),
                ('course_name', models.CharField(max_length=250)),
                ('course_url', models.URLField()),
                ('description', models.TextField()),
            ],
        ),
    ]
